New terms for annotating scRNAseq datasets
FlyBase/flybase-controlled-vocabulary pull request #139
Opened 2021-07-27 08:47 UTC by gouttegd

This PR adds a set of new terms that will be needed to annotate scRNAseq datasets for their inclusion into FlyBase.

It also assigns an ID range to me, since it's my first contribution to FBcv.

related to #138

2021-07-27 12:15 UTC, Clare72 requested changes

2021-07-27 12:15 UTC, Clare72 commented on src/ontology/fbcv-edit.obo
> +is_a: FBcv:0003082 ! result type
I think this is an 'analysis'.
some other stuff under 'result type', e.g. 'differential gene expression analysis' and 'expression clustering' should probably also be under 'analysis' too.

2021-07-27 12:19 UTC, Clare72 commented
Don't worry about failing checks, looks there was a problem downloading CHEBI (happens sometimes) - it will probably succeed next time (or you can just restart the travis build if it happens again).

2021-07-27 15:38 UTC, gouttegd commented on src/ontology/fbcv-edit.obo
> +is_a: FBcv:0003050 ! assay type
If we go that route, shouldn't `short RNA-Seq` also be a child a `RNA-Seq`?

2021-07-28 07:27 UTC, Clare72 commented on src/ontology/fbcv-edit.obo
> +is_a: FBcv:0003050 ! assay type
yes, it probably should

2021-07-28 08:58 UTC, gouttegd commented on src/ontology/fbcv-edit.obo
> +is_a: FBcv:0003050 ! assay type
This is done in the last commits I pushed. In the same vein I also moved all the `result type` terms that can reasonably be considered to refer to an "analysis" under the `analysis` term, as suggested in your comment below.

2021-07-28 09:25 UTC, Clare72 approved these changes

2021-07-28 09:59 UTC, merged